#                🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨
#           This file was automatically generated from src/transformers/models/rwkv7/modular_rwkv7.py.
#               Do NOT edit this file manually as any edits will be overwritten by the generation of
#             the file from the modular. If any change should be done, please apply the change to the
#                          modular_rwkv7.py file directly. One of our CI enforces this.
#                🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨
# Copyright 2026 The RWKV team and The HuggingFace Inc. team. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

from dataclasses import dataclass

import torch
from torch import nn

from ...generation import GenerationMixin
from ...modeling_layers import GradientCheckpointingLayer
from ...modeling_utils import PreTrainedModel
from ...utils import ModelOutput, auto_docstring
from ...utils.import_utils import is_triton_available
from .configuration_rwkv7 import Rwkv7Config


class Rwkv7TokenShift(nn.Module):
    """`prev_token(x)`: the previous token's hidden state, zero at sequence start.

    Carries one vector per layer per stream across forward calls, which is what
    makes incremental decoding exact rather than approximate.
    """

    def forward(
        self,
        x: torch.Tensor,
        shift_state: torch.Tensor | None,
        cu_seq_lens: torch.Tensor | None = None,
    ):
        # x: [batch, seq_len, hidden]; shift_state: [batch, hidden] or None
        if shift_state is None:
            prev = torch.zeros_like(x[:, :1])
        else:
            prev = shift_state[:, None]
        shifted = torch.cat([prev, x[:, :-1]], dim=1)
        if cu_seq_lens is not None:
            # In a packed row the token before a segment's first one belongs to the
            # PREVIOUS sequence. Resetting the recurrent state per segment does not
            # cover this — the shift reaches back through it — so the first token of
            # each segment gets the zero shift a sequence start is supposed to see.
            positions = torch.arange(x.shape[1], device=x.device)
            starts = (positions[:, None] == cu_seq_lens[None, :-1]).any(dim=1)
            shifted = torch.where(starts[None, :, None], torch.zeros_like(shifted), shifted)
        return shifted, x[:, -1]


# e^-0.5. The decay LoRA emits w_log = -INV_SQRT_E * sigmoid(...), so the
# per-step decay exp(w_log) lies in (e^-0.5, 1) — see RWKV-7 reference.
_INV_SQRT_E = 0.6065306597126334


def rwkv7_recurrent(
    r: torch.Tensor,
    w_log: torch.Tensor,
    k: torch.Tensor,
    v: torch.Tensor,
    kk: torch.Tensor,
    a: torch.Tensor,
    state: torch.Tensor,
    compute_dtype: torch.dtype = torch.float32,
) -> tuple[torch.Tensor, torch.Tensor]:
    """Reference RWKV-7 WKV recurrence (generalised delta rule).

    All inputs are `[batch, seq_len, num_heads, head_dim]`; `state` is
    `[batch, num_heads, head_dim, head_dim]` and is carried across calls.

    Per token, with `S` the per-head state and every product outer over the two
    head_dim axes::

        decay = exp(w_log)
        sa    = (-kk) @ S                 # uses the PRE-update state
        S     = decay * S + (kk * a) ⊗ sa + k ⊗ v
        out   = r @ S                     # uses the POST-update state

    The state axes are (key, value); `S[i, j]` accumulates key channel `i` against
    value channel `j`. Accumulation is fp32 regardless of the activation dtype —
    the recurrence is unrolled over the whole sequence, so a lower-precision state
    drifts. This is the portable path; a fused kernel may replace it as long as it
    reproduces these values.
    """
    batch, seq_len, num_heads, head_dim = r.shape
    dtype = r.dtype
    r, w_log, k, v, kk, a = (t.to(compute_dtype) for t in (r, w_log, k, v, kk, a))
    state = state.to(compute_dtype)
    out = torch.empty(batch, seq_len, num_heads, head_dim, device=r.device, dtype=compute_dtype)

    for t in range(seq_len):
        decay = torch.exp(w_log[:, t])[..., None]  # [B, H, K, 1]
        kk_t = kk[:, t]
        b = (kk_t * a[:, t])[..., None]  # [B, H, K, 1]
        # sa[b, h, j] = sum_i (-kk[b, h, i]) * S[b, h, i, j]
        sa = torch.einsum("bhi,bhij->bhj", -kk_t, state)[:, :, None, :]  # [B, H, 1, V]
        state = decay * state + b * sa + k[:, t][..., None] * v[:, t][:, :, None, :]
        out[:, t] = torch.einsum("bhi,bhij->bhj", r[:, t], state)

    return out.to(dtype), state


def rwkv7_chunked(
    r: torch.Tensor,
    w_log: torch.Tensor,
    k: torch.Tensor,
    v: torch.Tensor,
    kk: torch.Tensor,
    a: torch.Tensor,
    state: torch.Tensor,
    chunk_size: int = 16,
    compute_dtype: torch.dtype = torch.float32,
) -> tuple[torch.Tensor, torch.Tensor]:
    """Chunk-parallel form of [`rwkv7_recurrent`], for sequences.

    The step is `S_t = A_t S_{t-1} + k_t v_t^T` with `A_t = diag(w_t) - b_t kk_t^T`
    and `b_t = kk_t * a_t`, i.e. diagonal-plus-rank-one. Substituting
    `S_t = diag(c_t) P_t` with the running decay `c_t = prod_{s<=t} w_s` removes the
    diagonal part and leaves a plain delta rule::

        P_t = (I - b~_t q~_t^T) P_{t-1} + k~_t v_t^T
        b~ = b / c,  k~ = k / c,  q~ = kk * c_{t-1},  r~ = r * c

    Writing `u_t = q~_t^T P_{t-1}` turns a whole chunk into one unit-lower-triangular
    system, so the chunk is a handful of matmuls instead of `chunk_size` sequential
    steps; only the chunk-to-chunk carry stays serial::

        (I + tril(Q~ B~^T, -1)) U = Q~ P_0 + tril(Q~ K~^T, -1) V
        O   = R~ P_0 + tril(R~ K~^T, 0) V - tril(R~ B~^T, 0) U
        P_C = P_0 + K~^T V - B~^T U

    `chunk_size` is bounded by that division by `c`: the per-step decay is at least
    `e^-0.5`, so `1/c` grows like `e^(0.5 * chunk_size)` and 16 keeps it near 1e3 —
    comfortable in fp32, which is what this runs in regardless of activation dtype.
    """
    batch, seq_len, num_heads, head_dim = r.shape
    dtype = r.dtype
    r, w_log, k, v, kk, a = (t.to(compute_dtype) for t in (r, w_log, k, v, kk, a))
    state = state.to(compute_dtype)
    outputs = []

    for start in range(0, seq_len, chunk_size):
        stop = min(start + chunk_size, seq_len)
        span = stop - start
        w_c = torch.exp(w_log[:, start:stop])
        c = torch.cumprod(w_c, dim=1)
        c_prev = c / w_c
        b = kk[:, start:stop] * a[:, start:stop]

        b_t = b / c
        k_t = k[:, start:stop] / c
        q_t = kk[:, start:stop] * c_prev
        r_t = r[:, start:stop] * c
        v_c = v[:, start:stop]

        strict = torch.ones(span, span, device=r.device, dtype=r.dtype).tril(-1)
        causal = torch.ones(span, span, device=r.device, dtype=r.dtype).tril(0)

        qb = torch.einsum("bthn,bshn->bhts", q_t, b_t) * strict
        qk = torch.einsum("bthn,bshn->bhts", q_t, k_t) * strict
        eye = torch.eye(span, device=r.device, dtype=r.dtype)
        rhs = torch.einsum("bthn,bhnv->bhtv", q_t, state) + torch.einsum("bhts,bshv->bhtv", qk, v_c)
        u = torch.linalg.solve_triangular(eye + qb, rhs, upper=False, unitriangular=True)

        rk = torch.einsum("bthn,bshn->bhts", r_t, k_t) * causal
        rb = torch.einsum("bthn,bshn->bhts", r_t, b_t) * causal
        out_c = (
            torch.einsum("bthn,bhnv->bhtv", r_t, state)
            + torch.einsum("bhts,bshv->bhtv", rk, v_c)
            - torch.einsum("bhts,bhsv->bhtv", rb, u)
        )
        outputs.append(out_c.permute(0, 2, 1, 3))

        state = c[:, -1].unsqueeze(-1) * (
            state + torch.einsum("bthn,bthv->bhnv", k_t, v_c) - torch.einsum("bthn,bhtv->bhnv", b_t, u)
        )

    return torch.cat(outputs, dim=1).to(dtype), state


def rwkv7_eager(
    r: torch.Tensor,
    w_log: torch.Tensor,
    k: torch.Tensor,
    v: torch.Tensor,
    kk: torch.Tensor,
    a: torch.Tensor,
    state: torch.Tensor,
    cu_seq_lens: torch.Tensor | None = None,
    **kwargs,
) -> tuple[torch.Tensor, torch.Tensor]:
    """Portable WKV: the sequential step for a single token, chunk-parallel otherwise.

    With `cu_seq_lens` the row is a *packed* batch — several independent sequences
    laid end to end, the layout a varlen kernel consumes. Each one has to start
    from a fresh state, so they are run in turn and their outputs concatenated;
    the state returned is the last segment's, which is the one a continuation
    would resume from. This is the reference behaviour, not the fast path: a
    fused varlen kernel does the same segments in one launch, which is exactly
    the kind of implementation [`RWKV7_WKV_FUNCTIONS`] exists to let you drop in.
    """
    if cu_seq_lens is not None:
        bounds = cu_seq_lens.tolist()
        outputs = []
        for start, stop in zip(bounds[:-1], bounds[1:]):
            if stop <= start:
                continue
            segment_state = torch.zeros_like(state)
            out, state = rwkv7_eager(
                r[:, start:stop],
                w_log[:, start:stop],
                k[:, start:stop],
                v[:, start:stop],
                kk[:, start:stop],
                a[:, start:stop],
                segment_state,
            )
            outputs.append(out)
        return torch.cat(outputs, dim=1), state

    kernel = rwkv7_recurrent if r.shape[1] == 1 else rwkv7_chunked
    return kernel(r, w_log, k, v, kk, a, state)


RWKV7_WKV_FUNCTIONS = {"eager": rwkv7_eager}


class Rwkv7Attention(nn.Module):
    """RWKV-7 time-mixing block (the recurrent replacement for self-attention)."""

    def __init__(self, config: Rwkv7Config, layer_id: int):
        super().__init__()
        self.config = config
        self.layer_id = layer_id
        C = config.hidden_size
        self.hidden_size = C
        self.num_heads = config.num_heads
        self.head_dim = config.head_dim
        self.state_dtype = getattr(torch, config.wkv_state_dtype)

        self.time_shift = Rwkv7TokenShift()

        # per-channel token-shift mixes (kept at Bo's (1, 1, C) shape)
        self.x_r = nn.Parameter(torch.zeros(1, 1, C))
        self.x_w = nn.Parameter(torch.zeros(1, 1, C))
        self.x_k = nn.Parameter(torch.zeros(1, 1, C))
        self.x_v = nn.Parameter(torch.zeros(1, 1, C))
        self.x_a = nn.Parameter(torch.zeros(1, 1, C))
        self.x_g = nn.Parameter(torch.zeros(1, 1, C))

        # LoRA factors as raw tensors, exactly as the reference stores them
        self.w1 = nn.Parameter(torch.zeros(C, config.decay_low_rank_dim))
        self.w2 = nn.Parameter(torch.zeros(config.decay_low_rank_dim, C))
        self.w0 = nn.Parameter(torch.zeros(1, 1, C))
        self.a1 = nn.Parameter(torch.zeros(C, config.a_low_rank_dim))
        self.a2 = nn.Parameter(torch.zeros(config.a_low_rank_dim, C))
        self.a0 = nn.Parameter(torch.zeros(1, 1, C))
        self.g1 = nn.Parameter(torch.zeros(C, config.gate_low_rank_dim))
        self.g2 = nn.Parameter(torch.zeros(config.gate_low_rank_dim, C))
        # The value-residual LoRA exists on every layer in a reference checkpoint,
        # but layer 0 PRODUCES v_first instead of mixing towards it, so its copy is
        # never read. It is registered anyway so that loading is lossless.
        self.v1 = nn.Parameter(torch.zeros(C, config.v_low_rank_dim))
        self.v2 = nn.Parameter(torch.zeros(config.v_low_rank_dim, C))
        self.v0 = nn.Parameter(torch.zeros(1, 1, C))

        self.k_k = nn.Parameter(torch.zeros(1, 1, C))
        self.k_a = nn.Parameter(torch.zeros(1, 1, C))
        self.r_k = nn.Parameter(torch.zeros(config.num_heads, config.head_dim))

        self.receptance = nn.Linear(C, C, bias=False)
        self.key = nn.Linear(C, C, bias=False)
        self.value = nn.Linear(C, C, bias=False)
        self.output = nn.Linear(C, C, bias=False)
        # GroupNorm over heads, matching the reference's per-head normalisation.
        self.ln_x = nn.GroupNorm(config.num_heads, C, eps=config.norm_eps * config.num_heads)

    def forward(
        self,
        hidden_states: torch.Tensor,
        v_first: torch.Tensor | None,
        shift_state: torch.Tensor | None,
        wkv_state: torch.Tensor | None,
        keep: torch.Tensor | None = None,
        cu_seq_lens: torch.Tensor | None = None,
    ):
        batch, seq_len, C = hidden_states.shape
        H, N = self.num_heads, self.head_dim

        shifted, new_shift_state = self.time_shift(hidden_states, shift_state, cu_seq_lens)
        delta = shifted - hidden_states
        xr = hidden_states + self.x_r * delta
        xw = hidden_states + self.x_w * delta
        xk = hidden_states + self.x_k * delta
        xv = hidden_states + self.x_v * delta
        xa = hidden_states + self.x_a * delta
        xg = hidden_states + self.x_g * delta

        r = self.receptance(xr)
        k = self.key(xk)
        v = self.value(xv)

        w_log = -_INV_SQRT_E * torch.sigmoid(torch.tanh(xw @ self.w1) @ self.w2 + self.w0)
        a = torch.sigmoid(xa @ self.a1 @ self.a2 + self.a0)
        g = torch.sigmoid(xg @ self.g1) @ self.g2

        if keep is not None:
            # A padding position has to leave the recurrent state exactly as it
            # found it. The caller zeroes those positions, and all three
            # projections are bias-free, so k, v and kk are already zero there --
            # the update term k v^T is gone. What survives is the decay, and
            # w = exp(0) = 1 turns the transition into the identity.
            w_log = w_log * keep

        if self.layer_id == 0:
            v_first = v
        else:
            v = v + (v_first - v) * torch.sigmoid(xv @ self.v1 @ self.v2 + self.v0)

        kk = k * self.k_k
        kk = torch.nn.functional.normalize(kk.view(batch, seq_len, H, N), dim=-1, p=2.0).view(batch, seq_len, C)
        k = k * (1 + (a - 1) * self.k_a)

        if wkv_state is None:
            wkv_state = torch.zeros(batch, H, N, N, device=r.device, dtype=self.state_dtype)

        def _heads(t):
            return t.view(batch, seq_len, H, N)

        wkv = RWKV7_WKV_FUNCTIONS[self.config.wkv_implementation]
        y, wkv_state = wkv(
            _heads(r),
            _heads(w_log),
            _heads(k),
            _heads(v),
            _heads(kk),
            _heads(a),
            wkv_state,
            cu_seq_lens=cu_seq_lens,
        )

        y = self.ln_x(y.view(batch * seq_len, C)).view(batch, seq_len, C)
        # r·k·r_k summed per head, broadcast back over the head's value channels
        bonus = ((_heads(r) * _heads(k) * self.r_k).sum(dim=-1, keepdim=True) * _heads(v)).view(batch, seq_len, C)
        y = self.output((y + bonus) * g)
        return y, v_first, new_shift_state, wkv_state


_SPARSE_OP_READY = False


def _ensure_sparse_op() -> bool:
    """Import the Triton kernels once, outside anything that gets traced.

    A lazy `import` inside the forward is itself on dynamo's skip list, so doing
    this on the hot path breaks the graph at every layer even when the kernel is a
    properly registered custom op.
    """
    global _SPARSE_OP_READY
    if not _SPARSE_OP_READY and is_triton_available():
        from . import sparse_channel_mix  # noqa: F401  (registers the op)

        _SPARSE_OP_READY = True
    return _SPARSE_OP_READY


def sparse_channel_mix_value(
    activation: torch.Tensor, weight_t: torch.Tensor, accumulator: torch.Tensor
) -> torch.Tensor:
    """`out = activation @ weight_t`, reading only the rows the input selects.

    `activation` is `relu(key(x))**2`, so its zeros are EXACT and a zero channel
    contributes exactly nothing — skipping its weight row is not an approximation.
    On a 7.2B checkpoint ~93% of channels are zero while this projection is a third
    of the model's bytes, which is why it is worth a kernel at all.

    Only pays when kernel launches are captured (`torch.compile` with CUDA graphs).
    Eagerly it LOSES to one dense cuBLAS call, because the step is then bound by
    launch overhead rather than by the weight stream — measured both ways.
    Falls back to a dense matmul when Triton is unavailable.
    """
    if _SPARSE_OP_READY:
        return torch.ops.rwkv7.sparse_channel_mix_value(activation, weight_t, accumulator)
    return torch.nn.functional.linear(activation, weight_t.t())


class Rwkv7FeedForward(nn.Module):
    """RWKV-7 channel-mixing block: squared-ReLU over a single token shift."""

    def __init__(self, config: Rwkv7Config, layer_id: int):
        super().__init__()
        self.config = config
        self.layer_id = layer_id
        C = config.hidden_size
        self.time_shift = Rwkv7TokenShift()
        self.x_k = nn.Parameter(torch.zeros(1, 1, C))
        self.key = nn.Linear(C, config.intermediate_size, bias=False)
        self.value = nn.Linear(config.intermediate_size, C, bias=False)
        self._value_t = None  # [inter, hidden] copy for the sparse path, built lazily
        self._value_fingerprint = None
        self._accumulator = None

    def forward(
        self,
        hidden_states: torch.Tensor,
        shift_state: torch.Tensor | None,
        deep_embed: torch.Tensor | None = None,
        cu_seq_lens: torch.Tensor | None = None,
    ):
        shifted, new_shift_state = self.time_shift(hidden_states, shift_state, cu_seq_lens)
        xk = hidden_states + self.x_k * (shifted - hidden_states)
        inner = torch.relu(self.key(xk)) ** 2

        # RWKV-8 DeepEmbed: a per-layer, per-token vector that channelwise modulates
        # the channel-mix, supplied by the caller rather than stored as a weight
        # because the design keeps the table in RAM/SSD and prefetches per token.
        # Its width says which side it attaches to -- `intermediate_size` scales the
        # projection's INPUT (the reference "4x" variant), `hidden_size` its OUTPUT
        # ("1x"). Resolved once here so both the dense and sparse projections below
        # see the same decision; splitting it per branch is how the sparse path
        # silently dropped the 4x variant once already.
        scale_output = None
        if deep_embed is not None:
            if deep_embed.shape[-1] == inner.shape[-1]:
                inner = inner * deep_embed  # only rescales, so exact zeros survive
            else:
                scale_output = deep_embed

        out = self._project(inner)
        if scale_output is not None:
            out = out * scale_output
        return out, new_shift_state

    def _project(self, inner: torch.Tensor) -> torch.Tensor:
        """`value(inner)`, sparsely when that is both enabled and worthwhile.

        The sparse kernel decodes one token at a time on CUDA; anything else (a
        batch, a prefill, CPU) takes the dense projection, which is also what makes
        the two paths comparable in tests.
        """
        single_token = inner.shape[0] * inner.shape[1] == 1
        if self.config.sparse_channel_mix and single_token and inner.is_cuda:
            return self._sparse_value(inner.reshape(-1)).view(1, 1, -1)
        return self.value(inner)

    def _sparse_value(self, activation: torch.Tensor) -> torch.Tensor:
        """Value projection over only the nonzero channels of `relu(key(x))**2`.

        The transposed weight is built on first use rather than stored: the sparse
        read needs one contiguous row per input channel, which the `nn.Linear`
        layout does not give, and materialising it eagerly would cost every user
        the memory whether or not they enable this.
        """
        weight = self.value.weight
        if not torch.compiler.is_compiling():
            _ensure_sparse_op()
            # Tie the cache to the weight's identity AND its in-place version, so a
            # `mul_`, a fresh load, or a replaced parameter all invalidate it. A
            # cache that silently survives a weight change is worse than no cache.
            # Skipped while compiling: `data_ptr()` would break the graph, and the
            # weights cannot change inside a captured region anyway.
            fingerprint = (weight.data_ptr(), weight._version, weight.dtype)
            if self._value_t is None or self._value_fingerprint != fingerprint:
                self._value_t = weight.t().contiguous()
                self._accumulator = torch.zeros(weight.shape[0], device=weight.device, dtype=torch.float32)
                self._value_fingerprint = fingerprint
        return sparse_channel_mix_value(activation, self._value_t, self._accumulator)


class Rwkv7Block(GradientCheckpointingLayer):
    def __init__(self, config: Rwkv7Config, layer_id: int):
        super().__init__()
        self.config = config
        self.layer_id = layer_id
        eps, bias = config.norm_eps, config.norm_bias
        # Layer 0 carries the extra input norm of the reference implementation.
        if layer_id == 0:
            self.ln0 = nn.LayerNorm(config.hidden_size, eps=eps, bias=bias)
        self.ln1 = nn.LayerNorm(config.hidden_size, eps=eps, bias=bias)
        self.ln2 = nn.LayerNorm(config.hidden_size, eps=eps, bias=bias)
        self.att = Rwkv7Attention(config, layer_id)
        self.ffn = Rwkv7FeedForward(config, layer_id)

    def forward(
        self,
        hidden_states: torch.Tensor,
        v_first: torch.Tensor | None,
        state: list | None,
        deep_embed: torch.Tensor | None = None,
        keep: torch.Tensor | None = None,
        cu_seq_lens: torch.Tensor | None = None,
    ):
        if self.layer_id == 0:
            hidden_states = self.ln0(hidden_states)

        att_shift = state[0][self.layer_id] if state is not None else None
        ffn_shift = state[1][self.layer_id] if state is not None else None
        wkv = state[2][self.layer_id] if state is not None else None

        # Padding is blanked AFTER each norm, not before: a LayerNorm maps the zero
        # vector to its own bias, so masking the residual stream instead would let
        # every pad position come back to life on the way into the next mixer -- and
        # a live pad both moves the state and leaks into the next token's shift.
        attn_in = self.ln1(hidden_states)
        if keep is not None:
            attn_in = attn_in * keep
        attn_out, v_first, att_shift, wkv = self.att(attn_in, v_first, att_shift, wkv, keep, cu_seq_lens)
        hidden_states = hidden_states + attn_out

        ffn_in = self.ln2(hidden_states)
        if keep is not None:
            ffn_in = ffn_in * keep
        ffn_out, ffn_shift = self.ffn(ffn_in, ffn_shift, deep_embed, cu_seq_lens)
        hidden_states = hidden_states + ffn_out

        if state is not None:
            # Write into the pre-allocated slots rather than rebinding them: the
            # buffers then keep fixed addresses across steps, which is what lets a
            # captured CUDA graph replay the decode loop. Index assignment on the
            # list entries defeats that and silently drops the graph.
            state[0][self.layer_id].copy_(att_shift)
            state[1][self.layer_id].copy_(ffn_shift)
            state[2][self.layer_id].copy_(wkv)
        return hidden_states, v_first, state


@dataclass
class Rwkv7Output(ModelOutput):
    r"""
    state (`list[torch.FloatTensor]`, *optional*):
        The recurrent state: `[att_shift, ffn_shift, wkv]`, where the shifts are
        `[num_layers, batch, hidden]` and `wkv` is
        `[num_layers, batch, num_heads, head_dim, head_dim]`. Feed it back to
        continue a sequence; it replaces the KV cache and is O(1) in length.
    """

    last_hidden_state: torch.FloatTensor | None = None
    state: list[torch.FloatTensor] | None = None
    hidden_states: tuple[torch.FloatTensor, ...] | None = None


@dataclass
class Rwkv7CausalLMOutput(ModelOutput):
    r"""
    state (`list[torch.FloatTensor]`, *optional*):
        The recurrent state, as in [`Rwkv7Output`].
    """

    loss: torch.FloatTensor | None = None
    logits: torch.FloatTensor | None = None
    state: list[torch.FloatTensor] | None = None
    hidden_states: tuple[torch.FloatTensor, ...] | None = None


@auto_docstring
class Rwkv7PreTrainedModel(PreTrainedModel):
    config: Rwkv7Config
    base_model_prefix = "rwkv7"
    _no_split_modules = ["Rwkv7Block"]
    supports_gradient_checkpointing = True
    _is_stateful = True


@auto_docstring
class Rwkv7Model(Rwkv7PreTrainedModel):
    def __init__(self, config: Rwkv7Config):
        super().__init__(config)
        self.emb = nn.Embedding(config.vocab_size, config.hidden_size)
        self.blocks = nn.ModuleList([Rwkv7Block(config, i) for i in range(config.num_hidden_layers)])
        self.ln_out = nn.LayerNorm(config.hidden_size, eps=config.norm_eps, bias=config.norm_bias)
        self.gradient_checkpointing = False
        self.post_init()

    def get_input_embeddings(self):
        return self.emb

    def set_input_embeddings(self, new_embeddings):
        self.emb = new_embeddings

    def allocate_state(self, batch: int, device=None, dtype=None) -> list:
        """A zeroed recurrent state, with its buffers pinned for CUDA graphs.

        Allocate this yourself and pass it in as `state=` before compiling with a
        cudagraph mode. The pinning below only happens outside tracing --
        `mark_static_address` is not callable during compilation -- so a call that
        starts from `state=None` creates the buffers *inside* the compiled region,
        where they stay unpinned. Inductor then reports `skipping cudagraphs due to
        mutated inputs (3 instances)`, three being these buffers, and the decode
        loses the graphs it most needs.
        """
        return self._empty_state(
            batch,
            device if device is not None else self.emb.weight.device,
            dtype if dtype is not None else self.emb.weight.dtype,
        )

    def _empty_state(self, batch: int, device, dtype) -> list:
        cfg = self.config
        L, C, H, N = cfg.num_hidden_layers, cfg.hidden_size, cfg.num_heads, cfg.head_dim
        state = [
            torch.zeros(L, batch, C, device=device, dtype=dtype),
            torch.zeros(L, batch, C, device=device, dtype=dtype),
            torch.zeros(L, batch, H, N, N, device=device, dtype=getattr(torch, cfg.wkv_state_dtype)),
        ]
        # The recurrence writes into these buffers every step. Left as ordinary
        # inputs that would make the compiled region "mutate its inputs", which
        # disqualifies it from CUDA graphs -- and a recurrent decode is exactly the
        # workload that needs them. Pinning the addresses is what `StaticCache`
        # does for the same reason.
        if not torch.compiler.is_compiling():
            for buffer in state:
                torch._dynamo.mark_static_address(buffer)
        return state

    @auto_docstring
    def forward(
        self,
        input_ids: torch.LongTensor | None = None,
        attention_mask: torch.LongTensor | None = None,
        inputs_embeds: torch.FloatTensor | None = None,
        state: list[torch.FloatTensor] | None = None,
        deep_embeds: torch.FloatTensor | None = None,
        cu_seq_lens: torch.LongTensor | None = None,
        use_cache: bool | None = None,
        output_hidden_states: bool | None = None,
        return_dict: bool | None = None,
        **kwargs,
    ) -> tuple | Rwkv7Output:
        r"""
        state (`list[torch.FloatTensor]`, *optional*):
            Recurrent state returned by a previous call; pass it back to continue
            the sequence.
        deep_embeds (`torch.FloatTensor`, *optional*):
            RWKV-8 DeepEmbed vectors for this batch, shaped
            `[num_layers, batch, seq_len, deep_embed_size]` (or broadcastable).
            Only meaningful when `config.use_deep_embed` is set; the table itself is
            external to the checkpoint by design.
        cu_seq_lens (`torch.LongTensor`, *optional*):
            Cumulative sequence lengths for a *packed* batch — several sequences
            concatenated into one row instead of padded to a rectangle, starting at
            0 and ending at `seq_len`. Each segment then decodes from a fresh
            recurrent state, as if it had been run on its own. This is the varlen
            layout; use it instead of padding when the lengths vary a lot, since a
            recurrent model pays for pad tokens in time as well as memory.
        """
        output_hidden_states = (
            output_hidden_states if output_hidden_states is not None else self.config.output_hidden_states
        )
        use_cache = use_cache if use_cache is not None else self.config.use_cache
        return_dict = return_dict if return_dict is not None else self.config.use_return_dict

        if (input_ids is None) == (inputs_embeds is None):
            raise ValueError("Specify exactly one of input_ids or inputs_embeds")
        if inputs_embeds is None:
            inputs_embeds = self.emb(input_ids)

        if use_cache and state is None:
            state = self._empty_state(inputs_embeds.shape[0], inputs_embeds.device, inputs_embeds.dtype)

        # An attention-free recurrence has to be told where the padding is: pads are
        # fed through the recurrence like any other token, so a left-padded batch
        # (what `generate` produces) would otherwise start every short row from a
        # state the pads had already moved. A single decoded token is never padding,
        # so the decode step takes none of this.
        keep = None
        if attention_mask is not None and inputs_embeds.shape[1] > 1:
            keep = attention_mask[:, -inputs_embeds.shape[1] :, None].to(inputs_embeds.dtype)

        if cu_seq_lens is not None:
            # Checked rather than trusted: a malformed boundary list does not fail,
            # it silently splits the recurrence in the wrong places and returns
            # fluent output computed from the wrong states.
            if inputs_embeds.shape[0] != 1:
                raise ValueError(
                    f"cu_seq_lens describes one packed row, but got batch size {inputs_embeds.shape[0]}. "
                    "Pack the sequences into a single row, or use attention_mask with a padded batch."
                )
            if cu_seq_lens.ndim != 1 or cu_seq_lens[0] != 0 or cu_seq_lens[-1] != inputs_embeds.shape[1]:
                raise ValueError(
                    f"cu_seq_lens must be 1-D, start at 0 and end at seq_len ({inputs_embeds.shape[1]}); "
                    f"got {cu_seq_lens.tolist()}"
                )

        hidden_states = inputs_embeds
        v_first = None
        all_hidden_states = () if output_hidden_states else None

        for block in self.blocks:
            if output_hidden_states:
                all_hidden_states = all_hidden_states + (hidden_states,)
            layer_deep_embed = deep_embeds[block.layer_id] if deep_embeds is not None else None
            hidden_states, v_first, state = block(hidden_states, v_first, state, layer_deep_embed, keep, cu_seq_lens)

        hidden_states = self.ln_out(hidden_states)
        if output_hidden_states:
            all_hidden_states = all_hidden_states + (hidden_states,)

        if not return_dict:
            return tuple(x for x in (hidden_states, state, all_hidden_states) if x is not None)
        return Rwkv7Output(last_hidden_state=hidden_states, state=state, hidden_states=all_hidden_states)


@auto_docstring
class Rwkv7ForCausalLM(Rwkv7PreTrainedModel, GenerationMixin):
    _tied_weights_keys = {"head.weight": "rwkv7.emb.weight"}

    def __init__(self, config: Rwkv7Config):
        super().__init__(config)
        self.rwkv7 = Rwkv7Model(config)
        self.head = nn.Linear(config.hidden_size, config.vocab_size, bias=False)
        self.post_init()

    def get_output_embeddings(self):
        return self.head

    def set_output_embeddings(self, new_embeddings):
        self.head = new_embeddings

    def prepare_inputs_for_generation(self, input_ids, state=None, inputs_embeds=None, **kwargs):
        # Recurrent: once a state exists only the newest token is needed.
        if state is not None:
            input_ids = input_ids[:, -1:]
        model_inputs = (
            {"input_ids": input_ids}
            if inputs_embeds is None or state is not None
            else {"inputs_embeds": inputs_embeds}
        )
        model_inputs["state"] = state
        model_inputs.update({k: v for k, v in kwargs.items() if k in ("use_cache", "deep_embeds", "attention_mask")})
        return model_inputs

    @auto_docstring
    def forward(
        self,
        input_ids: torch.LongTensor | None = None,
        attention_mask: torch.LongTensor | None = None,
        inputs_embeds: torch.FloatTensor | None = None,
        state: list[torch.FloatTensor] | None = None,
        deep_embeds: torch.FloatTensor | None = None,
        labels: torch.LongTensor | None = None,
        use_cache: bool | None = None,
        output_hidden_states: bool | None = None,
        return_dict: bool | None = None,
        **kwargs,
    ) -> tuple | Rwkv7CausalLMOutput:
        r"""
        state (`list[torch.FloatTensor]`, *optional*):
            Recurrent state returned by a previous call.
        deep_embeds (`torch.FloatTensor`, *optional*):
            RWKV-8 DeepEmbed vectors; see [`Rwkv7Model.forward`].
        """
        return_dict = return_dict if return_dict is not None else self.config.use_return_dict
        outputs = self.rwkv7(
            input_ids=input_ids,
            attention_mask=attention_mask,
            inputs_embeds=inputs_embeds,
            state=state,
            deep_embeds=deep_embeds,
            use_cache=use_cache,
            output_hidden_states=output_hidden_states,
            return_dict=True,
            **kwargs,
        )
        logits = self.head(outputs.last_hidden_state)

        loss = None
        if labels is not None:
            loss = self.loss_function(logits, labels, self.config.vocab_size, **kwargs)

        if not return_dict:
            return (loss, logits, outputs.state) if loss is not None else (logits, outputs.state)
        return Rwkv7CausalLMOutput(loss=loss, logits=logits, state=outputs.state, hidden_states=outputs.hidden_states)


__all__ = ["Rwkv7PreTrainedModel", "Rwkv7Model", "Rwkv7ForCausalLM"]
